(cl:in-package intelli_mower-msg)
(cl:export '(HEADER-VAL
          HEADER
          COMMAND-VAL
          COMMAND
          BUMPERFRONT-VAL
          BUMPERFRONT
          BUMPERBACK-VAL
          BUMPERBACK
          EMERGENCY-VAL
          EMERGENCY
          CUTTER-VAL
          CUTTER
          LIFT-VAL
          LIFT
          LEFTSPEED-VAL
          LEFTSPEED
          RIGHTSPEED-VAL
          RIGHTSPEED
          OUTERRIGHT-VAL
          OUTERRIGHT
          INNERRIGHT-VAL
          INNERRIGHT
          INNERLEFT-VAL
          INNERLEFT
          OUTERLEFT-VAL
          OUTERLEFT
          XPOS-VAL
          XPOS
          YPOS-VAL
          YPOS
          HEADING-VAL
          HEADING
))